# Generated by Django 5.2.12 on 2026-04-01 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('HYPOTENSION', 'Hypotension'), ('DESATURATION', 'Desaturation'), ('BRADYCARDIA', 'Bradycardia'), ('TACHYCARDIA', 'Tachycardia'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('raised_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_comment', models.TextField(blank=True)),
                ('resolution_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthesia_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='casefile.anesthesiacase')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-raised_at'],
                'indexes': [models.Index(fields=['anesthesia_case', 'status'], name='alerts_anesthe_2a06c3_idx'), models.Index(fields=['alert_type', 'raised_at'], name='alerts_alert_t_e0e86e_idx')],
            },
        ),
    ]
