# Generated by Django 5.2.12 on 2026-03-29 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerOpEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('MEDICATION', 'Medication'), ('PROCEDURE', 'Procedure'), ('INCIDENT', 'Incident'), ('TECHNICAL', 'Technical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anesthesia_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perop_events', to='casefile.anesthesiacase')),
            ],
            options={
                'db_table': 'perop_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('administered_at', models.DateTimeField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administration', to='perop.peropevent')),
            ],
            options={
                'db_table': 'medication_administrations',
                'ordering': ['-administered_at'],
            },
        ),
        migrations.CreateModel(
            name='PerOpSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthesia_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perop_session', to='casefile.anesthesiacase')),
            ],
            options={
                'db_table': 'perop_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='peropevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='perop.peropsession'),
        ),
        migrations.CreateModel(
            name='VitalSignMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vital_type', models.CharField(choices=[('HEART_RATE', 'Heart Rate'), ('SYSTOLIC_BP', 'Systolic BP'), ('DIASTOLIC_BP', 'Diastolic BP'), ('MAP', 'Mean Arterial Pressure'), ('SPO2', 'SpO2'), ('ETCO2', 'EtCO2'), ('RESPIRATORY_RATE', 'Respiratory Rate'), ('TEMPERATURE', 'Temperature')], max_length=40)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('source_device', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_measurements', to='perop.peropsession')),
            ],
            options={
                'db_table': 'vital_sign_measurements',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='peropevent',
            index=models.Index(fields=['anesthesia_case', 'timestamp'], name='perop_event_anesthe_b8192b_idx'),
        ),
        migrations.AddIndex(
            model_name='peropevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='perop_event_event_t_72ba56_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsignmeasurement',
            index=models.Index(fields=['session', 'recorded_at'], name='vital_sign__session_feaedb_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsignmeasurement',
            index=models.Index(fields=['vital_type', 'recorded_at'], name='vital_sign__vital_t_cdf132_idx'),
        ),
    ]
