# Generated by Django 5.2.12 on 2026-03-26 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnesthesiaCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRE_OP', 'Pre-op'), ('PER_OP', 'Per-op'), ('POST_OP', 'Post-op'), ('CLOSED', 'Closed')], default='PRE_OP', max_length=20)),
                ('surgery_type', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anesthesia_cases', to='patient.patient')),
            ],
            options={
                'db_table': 'anesthesia_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
