# Generated by Django 5.2.11 on 2026-03-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casefile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anesthesiacase',
            name='decision',
            field=models.CharField(blank=True, choices=[('AUTHORIZED', 'Autoriser l’anesthésie'), ('EXAMS_REQUIRED', 'Demander des examens complémentaires'), ('SPECIALIST_OPINION', 'Demander un avis spécialisé'), ('REFUSED', 'Récuser l’anesthésie')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='anesthesiacase',
            name='decision_notes',
            field=models.TextField(blank=True),
        ),
    ]
