# Generated by Django 5.2.12 on 2026-03-26 01:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOpQuestionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('validation_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VALIDATED', 'Validated'), ('CORRECTED', 'Corrected')], default='DRAFT', max_length=20)),
                ('has_allergies', models.BooleanField(default=False)),
                ('allergy_details', models.TextField(blank=True)),
                ('current_treatment', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('smoker', models.BooleanField(default=False)),
                ('alcohol_use', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthesia_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preop_questionnaire', to='casefile.anesthesiacase')),
            ],
            options={
                'db_table': 'preop_questionnaires',
                'ordering': ['-created_at'],
            },
        ),
    ]
