# Generated by Django 5.2.12 on 2026-03-26 01:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casefile', '0001_initial'),
        ('preop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preopquestionnaire',
            name='alcohol_use',
        ),
        migrations.RemoveField(
            model_name='preopquestionnaire',
            name='allergy_details',
        ),
        migrations.RemoveField(
            model_name='preopquestionnaire',
            name='current_treatment',
        ),
        migrations.RemoveField(
            model_name='preopquestionnaire',
            name='has_allergies',
        ),
        migrations.RemoveField(
            model_name='preopquestionnaire',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='preopquestionnaire',
            name='smoker',
        ),
        migrations.AlterField(
            model_name='preopquestionnaire',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic')], default='fr', max_length=5),
        ),
        migrations.CreateModel(
            name='ClinicalScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_type', models.CharField(choices=[('DUKE', 'Duke / METs'), ('LEE', 'Lee / RCRI'), ('STOP_BANG', 'STOP-BANG'), ('APFEL', 'Apfel'), ('GOLD', 'GOLD'), ('CHILD_PUGH', 'Child-Pugh'), ('NYHA', 'NYHA'), ('CHA2DS2_VASC', 'CHA2DS2-VASc'), ('ARISCAT', 'ARISCAT')], max_length=30)),
                ('score_value', models.CharField(max_length=100)),
                ('score_details', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('anesthesia_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_scores', to='casefile.anesthesiacase')),
            ],
            options={
                'db_table': 'clinical_scores',
                'ordering': ['score_type'],
                'unique_together': {('anesthesia_case', 'score_type')},
            },
        ),
        migrations.CreateModel(
            name='PreOpQuestionnaireResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=100)),
                ('question_code', models.CharField(max_length=100)),
                ('question_label_fr', models.CharField(blank=True, max_length=255)),
                ('question_label_ar', models.CharField(blank=True, max_length=255)),
                ('answer_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('CHOICE', 'Choice'), ('MULTI_CHOICE', 'Multi choice'), ('DATE', 'Date')], default='TEXT', max_length=20)),
                ('answer_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='preop.preopquestionnaire')),
            ],
            options={
                'db_table': 'preop_questionnaire_responses',
                'ordering': ['section', 'question_code'],
                'unique_together': {('questionnaire', 'question_code')},
            },
        ),
    ]
