# Generated by Django 5.2.12 on 2026-03-27 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preop', '0002_remove_preopquestionnaire_alcohol_use_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=100)),
                ('question_code', models.CharField(max_length=100, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_ar', models.CharField(blank=True, max_length=255)),
                ('answer_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('CHOICE', 'Choice'), ('MULTI_CHOICE', 'Multi choice'), ('DATE', 'Date')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('used_for_scores', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_templates',
                'ordering': ['section', 'question_code'],
            },
        ),
    ]
