# Generated by Django 5.2.11 on 2026-03-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preop', '0003_questiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
