# Generated by Django 5.2.12 on 2026-03-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preop', '0003_questiontemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalscore',
            name='score_type',
            field=models.CharField(choices=[('DUKE', 'Duke / METs'), ('LEE', 'Lee / RCRI'), ('STOP_BANG', 'STOP-BANG'), ('APFEL', 'Apfel'), ('GOLD', 'GOLD'), ('CHILD_PUGH', 'Child-Pugh'), ('NYHA', 'NYHA'), ('CHA2DS2_VASC', 'CHA2DS2-VASc'), ('ARISCAT', 'ARISCAT'), ('ALDRETE', 'Aldrete')], max_length=30),
        ),
    ]
