# Generated by Django 5.2.11 on 2026-04-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preop', '0004_alter_clinicalscore_score_type'),
        ('preop', '0004_questiontemplate_choices'),
    ]

    operations = [
    ]
