# Generated by Django 5.2.11 on 2026-03-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patient_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
