# Generated by Django 5.2.12 on 2026-03-31 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOpStay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthesia_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postop_stay', to='casefile.anesthesiacase')),
            ],
            options={
                'db_table': 'postop_stays',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PostOpObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_time', models.DateTimeField()),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activity_score', models.PositiveSmallIntegerField(default=0)),
                ('respiration_score', models.PositiveSmallIntegerField(default=0)),
                ('circulation_score', models.PositiveSmallIntegerField(default=0)),
                ('consciousness_score', models.PositiveSmallIntegerField(default=0)),
                ('oxygenation_score', models.PositiveSmallIntegerField(default=0)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='postop.postopstay')),
            ],
            options={
                'db_table': 'postop_observations',
                'ordering': ['-observation_time'],
                'indexes': [models.Index(fields=['stay', 'observation_time'], name='postop_obse_stay_id_d693b9_idx')],
            },
        ),
    ]
